openapi: 3.0.3
info:
  title: VyrapApp
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8181'
paths:
  /api/auth/register:
    post:
      summary: 'Yeni kullanıcı kayıt'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 4
                  name: 'Jessica Jones'
                  email: test@test.com
                  twitter_account: vyralapp
                  phone: '5551112233'
                  token: 5|ESIpqgOQzqkmZ2jkmwZE20l3BthE5UygkUUctyBi
                  token_type: Bearer
                properties:
                  id:
                    type: integer
                    example: 4
                  name:
                    type: string
                    example: 'Jessica Jones'
                  email:
                    type: string
                    example: test@test.com
                  twitter_account:
                    type: string
                    example: vyralapp
                  phone:
                    type: string
                    example: '5551112233'
                  token:
                    type: string
                    example: 5|ESIpqgOQzqkmZ2jkmwZE20l3BthE5UygkUUctyBi
                  token_type:
                    type: string
                    example: Bearer
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: vitae
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: okling@example.net
                phone:
                  type: string
                  description: 'Must be at least 10 characters. Must not be greater than 10 characters.'
                  example: nxv
                password:
                  type: string
                  description: ''
                  example: sit
                twitter_account:
                  type: string
                  description: ''
                  example: et
              required:
                - name
                - email
                - phone
                - password
                - twitter_account
      security: []
  /api/auth/login:
    post:
      summary: 'Oturum aç'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: akeebler@example.net
                password:
                  type: string
                  description: ''
                  example: velit
              required:
                - email
                - password
      security: []
  /api/auth/verify/email:
    post:
      summary: 'E-posta adresi doğrulama'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: id
                code:
                  type: string
                  description: 'Must be at least 4 characters. Must not be greater than 4 characters.'
                  example: ''
              required:
                - email
                - code
      security: []
  /api/auth/verify/phone:
    post:
      summary: 'Telefon numarası doğrulama'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: ''
                  example: ut
                code:
                  type: string
                  description: 'Must be at least 4 characters. Must not be greater than 4 characters.'
                  example: o
              required:
                - phone
                - code
      security: []
  /api/profile/importLastTwentyTwits:
    post:
      summary: 'Son 20 twiti içe aktar'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Profile
  /api/twit:
    get:
      summary: 'Twit listesi'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Twit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twitter_account:
                  type: string
                  description: ''
                  example: dolore
              required:
                - twitter_account
    post:
      summary: 'Yeni twit ekle'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Twit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twit:
                  type: string
                  description: ''
                  example: explicabo
                status:
                  type: boolean
                  description: ''
                  example: true
              required:
                - twit
                - status
  '/api/twit/{id}':
    get:
      summary: 'Twit görüntüle'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Twit
    put:
      summary: 'Twit güncelle'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Twit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twit:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: hsqvtwufoslrxvqihrehldbrrqcwgtjwficcagzfgzyexjjylhmabdlafaxhwanlbjxdwdtcztrzxmcftttvwmiexnzpvbkrowijlkmzvnjrkqbgqemtkhhimfeqzgbpxefnykayjlxjoucfcbmhkgvcnvdaiecdzufcvzywfxpayqqyjarxacywfpjncpplnfeznkexsaoelqhxenaogdpaqlyeamducmveavpenmvuqkuuarznqgvkkxhioydmzwigymttywjhxtyihbmymebkdbdinixivujoaedarrbltallglrhchulfgziuisyqswdlbsvipeodtbftawcnagnalgqjncvraihcxumfatstndcedntugmmyirvvmjkiorwbwrfzebsadquqiluvohlxcrrtvtbpsoaalqahsjhfykzxxffwattqvhlbsuvoqspzkvmqivjleilkhsjvsuytnebsdqjswzqjgsalkrxbfgqksvltp
                status:
                  type: boolean
                  description: ''
                  example: true
              required:
                - twit
                - status
    delete:
      summary: 'Twit sil'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Twit
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the twit.'
        example: 13
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: ''
  -
    name: Profile
    description: ''
  -
    name: Twit
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
